k3s_channel: "{{ lookup('env', 'K3S_CHANNEL') | default('v1.34', true) }}"
k3s_version: "{{ lookup('env', 'K3S_VERSION') | default('', true) }}"
k3s_config_dir: /etc/rancher/k3s
k3s_kubeconfig: /etc/rancher/k3s/k3s.yaml
kai_version: "{{ lookup('env', 'KAI_VERSION') | default('v0.16.5', true) }}"
fake_gpu_operator_version: "{{ lookup('env', 'FAKE_GPU_OPERATOR_VERSION') | default('0.2.0', true) }}"
kwok_version: "{{ lookup('env', 'KWOK_VERSION') | default('v0.7.0', true) }}"
