apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kai-scheduler
  namespace: kai-scheduler
  labels:
    kai-scheduler-101/chapter: "19"
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kai-scheduler-default
  namespaceSelector:
    matchNames: [kai-scheduler]
  endpoints:
    - port: http-metrics
      interval: 30s
