apiVersion: v1
kind: Node
metadata:
  name: kwok-gpu-01
  labels:
    kai.scheduler/node-pool: placement-spread
---
apiVersion: v1
kind: Node
metadata:
  name: kwok-gpu-02
  labels:
    kai.scheduler/node-pool: placement-spread
---
apiVersion: v1
kind: Node
metadata:
  name: kwok-gpu-03
  labels:
    kai.scheduler/node-pool: placement-binpack
---
apiVersion: v1
kind: Node
metadata:
  name: kwok-gpu-04
  labels:
    kai.scheduler/node-pool: placement-binpack
