apiVersion: kai.scheduler/v1
kind: SchedulingShard
metadata:
  name: binpack-demo
  labels:
    kai-scheduler-101/chapter: "16"
spec:
  partitionLabelKey: kai.scheduler/node-pool
  partitionLabelValue: placement-binpack
  placementStrategy:
    cpu: binpack
