apiVersion: v1
kind: Namespace
metadata:
  name: kai-lab05
  labels:
    kai-scheduler-101/chapter: "05"
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: gpu-one
  namespace: kai-lab05
  labels:
    kai-scheduler-101/chapter: "05"
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly: { allocationMode: ExactCount, count: 1, deviceClassName: gpu.nvidia.com }
