apiVersion: kai.scheduler/v1
kind: SchedulingShard
metadata:
  name: h100-shard
  labels:
    kai-scheduler-101/chapter: "17"
spec:
  partitionLabelValue: h100
  args:
    actions: [allocate, consolidate, reclaim, preempt, stalegangeviction]
