apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podcliquesets.grove.io
  labels:
    kai-scheduler-101/chapter: "14"
spec:
  group: grove.io
  scope: Namespaced
  names:
    plural: podcliquesets
    singular: podcliqueset
    kind: PodCliqueSet
    shortNames: [pcs]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podcliquescalinggroups.grove.io
  labels:
    kai-scheduler-101/chapter: "14"
spec:
  group: grove.io
  scope: Namespaced
  names:
    plural: podcliquescalinggroups
    singular: podcliquescalinggroup
    kind: PodCliqueScalingGroup
    shortNames: [pcsg]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podcliques.grove.io
  labels:
    kai-scheduler-101/chapter: "14"
spec:
  group: grove.io
  scope: Namespaced
  names:
    plural: podcliques
    singular: podclique
    kind: PodClique
    shortNames: [pclq]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podgangs.grove.io
  labels:
    kai-scheduler-101/chapter: "14"
spec:
  group: grove.io
  scope: Namespaced
  names:
    plural: podgangs
    singular: podgang
    kind: PodGang
    shortNames: [pgang]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
