apiVersion: kai.scheduler/v1
kind: SchedulingShard
metadata:
  name: time-fairshare-demo
  labels:
    kai-scheduler-101/chapter: "09"
spec:
  partitionLabelValue: default
  kValue: 0.5
  usageDBConfig:
    clientType: prometheus
    usageParams:
      windowSize: 1w
      windowType: sliding
      halfLifePeriod: 1h
