apiVersion: v1
kind: Namespace
metadata:
  name: namespace-a
  labels: { kai-scheduler-101/chapter: "19" }
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-b
  labels: { kai-scheduler-101/chapter: "19" }
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-c
  labels: { kai-scheduler-101/chapter: "19" }
---
apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
  name: gpu-sharing-demo
  labels: { kai-scheduler-101/chapter: "19" }
spec:
  resources:
    gpu: { quota: 1, limit: 1, overQuotaWeight: 1 }
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: gpu-one
  namespace: namespace-a
  labels: { kai-scheduler-101/chapter: "19" }
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly: { allocationMode: ExactCount, count: 1, deviceClassName: gpu.nvidia.com }
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: gpu-one
  namespace: namespace-b
  labels: { kai-scheduler-101/chapter: "19" }
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly: { allocationMode: ExactCount, count: 1, deviceClassName: gpu.nvidia.com }
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: gpu-one
  namespace: namespace-c
  labels: { kai-scheduler-101/chapter: "19" }
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly: { allocationMode: ExactCount, count: 1, deviceClassName: gpu.nvidia.com }
